### ISSUE TITLE
Doesn't work on xcode 7

### ISSUE THREAD

**Issue by mirzadelic** [frederik-jacques/TNSwiftyCheckboxGroup#1]
Too much errors on xcode 7, can't build.

**Comment by frederik-jacques** [comment]
Could you elaborate a bit more?  Are you using it via CocoaPods?
I've just checked and it works fine on Xcode 7.0.1.

**Comment by swabzz** [comment]
Not working with xcode Version 7.2.1 and swift 2, too much errors

**Comment by ghost** [comment]
I tried on XCode 7.3 and Swift 2.2 and can confirm that it doesn't compile. It generated 11 errors. I installed it via CocoaPods

**Comment by frederik-jacques** [comment]
Ill check tonight

**Comment by frederik-jacques** [comment]
Fixed & updated podspec file
